name: Highcharts webpack monitoring

on: workflow_call

jobs:
  test_webpack:
    name: Webpack tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr
      - uses: browser-actions/setup-geckodriver@latest

      - name: Install Dependencies
        run: npm i

      - name: Check Firefox
        run: |
          firefox --version
          whereis firefox

      - name: Test Webpacks with Firefox
        run: |
          export DISPLAY=:99
          npx gulp test --webpack --single-run --splitbrowsers Firefox --force

      - name: Output logged errors
        run: cat ./test/console.log

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PR_COMMENT_TOKEN}}
          script: |
            const { createOrUpdateComment } = require('./.github/scripts/commentOnPR');
            const { readFileSync } = require('node:fs')

            const testLog = readFileSync('./test/console.log');

            await createOrUpdateComment(github, context, 'Webpack monitoring',
              testLog ?
                ':rotating_light: Webpack tests failed.' +
                ' Check demos and masters!' :
                'LGTM :+1:'
            );
